spring.application.name=CV-Checker
gemini.api.key=AIzaSyCzAAgsV_p8MpPbn7MB5a91vJu8KFefbf0
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
gemini.modelName = gemini-2.0-flash-exp